import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "../components/Header/Navbar.jsx";
import Footer from "../components/Footer/Footer.jsx";
import SmoothScrollInit from "../components/SmoothScrollInit.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NovaHealth Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Navbar />

        {/* Smooth Scroll Initialization */}
        <SmoothScrollInit />

        <main className="flex-grow">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
